global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Threading;
global using FileDownloaderWithProgressDemo.Domain;
global using FileDownloaderWithProgressDemo.Utils;
global using FileDownloaderWithProgressDemo.Services;